AF-Feb2022 newsletter fixes
parameter1/allured-business-media-newsletters pull request #60
Opened 2022-02-14 23:29 UTC by afrederick

[DPP-4937] & [DPP-4916] @solocommand @brandonbk 
Fixes for Outlook conditional comments and a fix for the cropping and resolution problem on the hero images. 

### Outlook Ad Background and spacing issue
Before: 
<img width="500" alt="outlook-before" src="https://user-images.githubusercontent.com/106970/153963556-bf087b56-1f7d-4639-acaf-8308d03d6c3c.jpg">

After:
<img width="500" alt="outlook-after" src="https://user-images.githubusercontent.com/106970/153963565-5fa4bc95-341e-46b2-8641-c4870d15c48b.jpg">

### Hero image cropping and resolution
Before (yes, it actually ran like this...):
<img width="500" alt="hero-image-before" src="https://user-images.githubusercontent.com/106970/153963580-b3013a5f-f318-4bc0-9848-0ebb7422b745.png">

After:
<img width="500" alt="hero-image-fix" src="https://user-images.githubusercontent.com/106970/153963594-49f4a2e9-141a-4a06-bc0f-a8624199d276.png">

2022-02-14 23:52 UTC, brandonbk requested changes

2022-02-14 23:52 UTC, brandonbk commented on tenants/all/templates/components/daily-element-content-hero.marko
> +        ...!image.isLogo && { fit: "crop",crop:"faces" },
Add a space after the comma and colon: `{ fit: "crop", crop: "faces" }`

No lint rules in these files to catch that, but just something to keep clean if possible.

2022-02-14 23:52 UTC, brandonbk commented on packages/common/components/dpm/emailx.marko
> +      <!--[if (gte mso 9)|(lte IE 9)]><table width='600' bgcolor='#E5E5E5' align='center' cellpadding='0' cellspacing='0' border='0' style='margin:0px; padding:0px; border-collapse:collapse; backgrou
The first conditional comment uses single quotes for attribute values, but the second uses double quotes...is this intentional?  If not, as picky as Outlook is it might be best to standardize on one or the other to eliminate variability.

2022-02-14 23:58 UTC, afrederick commented on packages/common/components/dpm/emailx.marko
> +      <!--[if (gte mso 9)|(lte IE 9)]><table width='600' bgcolor='#E5E5E5' align='center' cellpadding='0' cellspacing='0' border='0' style='margin:0px; padding:0px; border-collapse:collapse; backgrou
@brandonbk - Good catch. I was copying and pasting from different sources. Updates for both of these should be coming through.

2022-02-15 21:08 UTC, afrederick commented
@brandonbk - I just wanted to check that I submitted the revisions correctly. Do I need to mark the conversations as resolved, or just leave them as is?

2022-02-15 21:30 UTC, Shinsina approved these changes

2022-02-15 21:32 UTC, merged

2022-02-15 21:33 UTC, Shinsina commented
@afrederick Apologies for the delay on getting these merged, should be deployed shortly. We'll handle resolving the conversations, helps us make sure changes were addressed in the right places etc.

2022-02-15 21:58 UTC, afrederick commented
@Shinsina - No worries. I just wanted to make sure you weren't waiting on me for something else. Thank you for getting this merged!