Create WPC product roundup newsletter
parameter1/allured-business-media-newsletters pull request #61
Opened 2022-02-22 16:51 UTC by jwade1327

![screencapture-localhost-22090-templates-wpc-product-roundup-2022-02-22-10_48_12](https://user-images.githubusercontent.com/64623209/155179718-12f5b61a-8612-4a37-917d-f187b65ca578.png)

2022-02-22 16:52 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [New deployment for WPC Product Round Up](https://trello.com/c/DUELXHJ9/283-new-deployment-for-wpc-product-round-up)

2022-02-22 17:07 UTC, Shinsina requested changes

2022-02-22 17:07 UTC, Shinsina commented on tenants/all/templates/components/daily-header-full.marko
> +$ const wpcLogoStyles = {
It looks like the only difference between this component and https://github.com/parameter1/allured-business-media-newsletters/blob/master/tenants/all/templates/components/daily-header.marko is things regarding the height of the image display (found on line 35 in attached and 34 on the file added in this PR this comment is on). 

Rather than making an entire component for what equates to a one line change. I would either pass in the changed attributes to whatever values they should or shouldn't be (likely what may be the easiest is in this particular newsletter template define what is labeled as wpCLogoStyles in the currently added component as logoStyles and use that if it's defined otherwise use the default that was already in: https://github.com/parameter1/allured-business-media-newsletters/blob/master/tenants/all/templates/components/daily-header.marko. (logoStyles)

It may also be possible to check attributes one by one and checking if they exist and using them if they do something like this:
<img width="632" alt="Screen Shot 2022-02-22 at 11 06 50 AM" src="https://user-images.githubusercontent.com/46794001/155182217-851a497c-02e7-4e2f-b827-90fd65046cde.png">

2022-02-22 17:07 UTC, Shinsina commented on tenants/all/templates/wpc-product-roundup.marko
> +      <daily-header-full
Change this to use ```daily-header``` using the previously mentioned additional input.

2022-02-24 15:23 UTC, Shinsina requested changes

2022-02-24 15:23 UTC, Shinsina commented on tenants/all/templates/components/daily-header-full.marko
> +
Is this file still necessary to have? I think the changes made to the other daily-header makes this one unused/unnecessary.

2022-02-24 15:23 UTC, Shinsina commented on tenants/all/templates/wpc-product-roundup.marko
> +$ const logoHeightInput = input;
Where is this being passed in from? If you're looking for keys/properties off of input they should be accessed using object destructuring or some sort of base-cms/object-path function call (like get() or getAsArray etc.) ``` $ const { logoHeightInput } = input```.

2022-02-24 15:23 UTC, Shinsina commented on tenants/all/templates/wpc-product-roundup.marko
> +        logo-height-input={ height: 275 }
It looks like the above pass in as input is unnecessary as it's being pass in statically here, was this causing any issues without the quotes on the key? (height in this case), should probably be consistent regardless and add them here even if they aren't technically necessary as the rest of the logo style keys have them.

2022-02-24 15:23 UTC, Shinsina commented on tenants/all/templates/components/daily-header.marko
> +        <marko-newsletter-imgix src=input.imageSrc options={ w: 600 } alt=input.name attrs={ border: 0, width: 600, style: logoStyles}>
Put the space back after logoStyles.

2022-02-24 15:31 UTC, jwade1327 commented on tenants/all/templates/components/daily-header-full.marko
> +
@Shinsina This part wasn't altered.

2022-02-24 15:33 UTC, Shinsina commented on tenants/all/templates/components/daily-header-full.marko
> +
@jwade1327 Is this component still being used anywhere? https://github.com/parameter1/allured-business-media-newsletters/pull/61/commits/4b3379ddeb9ccf5bc4f61f873e3fecc5bef78b40 Leads me to believe it isn't and can safely be removed, unless there is somewhere else using this?

2022-02-24 15:40 UTC, Shinsina commented on tenants/all/templates/components/daily-header.marko
>  $ const { previewText } = input;
This should probably be removed too as it appears to now be unused.

2022-02-24 15:46 UTC, Shinsina commented on tenants/all/templates/components/daily-header.marko
>  $ const { previewText } = input;
@jwade1327 Was referring to the ``` $ const { previewText } = input; ``` however the defaultValue import should stay as that is still being used for the logoHeightInput.

2022-02-24 16:30 UTC, Shinsina approved these changes

2022-02-24 16:30 UTC, merged